import Avatar1 from "./images/boy.png";
import Avatar2 from "./images/doc_boy.png";
import Avatar3 from "./images/simple_boy.png";
import Avatar4 from "./images/suit_boy.png";
import Avatar5 from "./images/doc_girl.png";

export const students = [
  {
    id: 1,
    image: Avatar1,
    alt: "Student 1",
    name: "Ali Mustafa",
    title: "Student at CODED.",
    email: "alimustafa@example.com",
    snack: "Fruit snacks",
    emoji: "😁",
    grade: "90%",
  },
  {
    id: 2,
    image: Avatar5,
    alt: "Student 2",
    name: "Nora Hussein",
    title: "Student at CODED.",
    email: "norahussein@example.com",
    snack: "Chocolate",
    emoji: "😎",
    grade: "78%",
  },
  {
    id: 3,
    image: Avatar5,
    alt: "Student 3",
    name: "Layla Abdulrahman",
    title: "Student at CODED.",
    email: "laylaabdulrahman@example.com",
    snack: "Protein bars",
    emoji: "😊",
    grade: "86%",
  },
  {
    id: 4,
    image: Avatar2,
    alt: "Student 4",
    name: "Mohammed Khalil",
    title: "Student at CODED.",
    email: "mohammedkhalil@example.com",
    snack: "Ice cream",
    emoji: "😇",
    grade: "91%",
  },
  {
    id: 5,
    image: Avatar3,
    alt: "Student 5",
    name: "Ahmed Saleh",
    title: "Student at CODED.",
    email: "ahmedsaleh@example.com",
    snack: "Popcorn",
    emoji: "😀",
    grade: "70%",
  },
  {
    id: 6,
    image: Avatar5,
    alt: "Student 6",
    name: "Fatima Ali",
    title: "Student at CODED.",
    email: "fatimaali@example.com",
    snack: "Dried fruit",
    emoji: "🤨",
    grade: "88%",
  },
  {
    id: 7,
    image: Avatar5,
    alt: "Student 7",
    name: "Yasmin Hamdan",
    title: "Student at CODED.",
    email: "yasminhamdan@example.com",
    snack: "Veggie sticks",
    emoji: "😉",
    grade: "95%",
  },
  {
    id: 8,
    image: Avatar3,
    alt: "Student 8",
    name: "Abdullah Mahmoud",
    title: "Student at CODED.",
    email: "abdullahmahmoud@example.com",
    snack: "Chips",
    emoji: "😑",
    grade: "80%",
  },
  {
    id: 9,
    image: Avatar5,
    alt: "Student 9",
    name: "Sara Mohammed",
    title: "Student at CODED.",
    email: "saramohammed@example.com",
    snack: "Yogurt cups",
    emoji: "🤗",
    grade: "82%",
  },
  {
    id: 10,
    image: Avatar4,
    alt: "Student 10",
    name: "Omar Hassan",
    title: "Student at CODED.",
    email: "omarhassan@example.com",
    snack: "Cheese and crackers",
    emoji: "😄",
    grade: "93%",
  },
];
